Assignment 6 — Numpy-II

Q1. Consider the following sensor readings:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
A sensor has an average measurement error of +2°C.

Perform the following without using a for loop:

a. Add 2°C to every reading using vectorization.

b. Convert all temperatures from Celsius to Fahrenheit using:
F = (9
/5)*C + 32

c. Identify all readings greater than 32°C using Boolean indexing.

d. Count how many readings exceed 32°C.

e. Explain how vectorization and Boolean indexing can make data processing more efficient
than explicitly iterating through every value

In [3]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# a. Add 2°C
corrected_temperature = temperature + 2

print("Original temperature:")
print(temperature)

print("\nCorrected temperature:")
print(corrected_temperature)

# b. Convert to Fahrenheit
fahrenheit = (9 / 5) * corrected_temperature + 32

print("\nTemperature in Fahrenheit:")
print(fahrenheit)

# c. Readings greater than 32°C
above_32 = corrected_temperature[corrected_temperature > 32]

print("\nReadings greater than 32°C:")
print(above_32)

# d. Count readings greater than 32°C
count = np.sum(corrected_temperature > 32)

print("\nNumber of readings greater than 32°C:", count)

Original temperature:
[25 28 31 35 38 27 33 40]

Corrected temperature:
[27 30 33 37 40 29 35 42]

Temperature in Fahrenheit:
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]

Readings greater than 32°C:
[33 37 40 35 42]

Number of readings greater than 32°C: 5


Q2. The following matrix represents the number of daily steps recorded by four users
over three days:

steps = np.array([

[5000, 6200, 7100],

[8000, 7500, 9000],

[4500, 5100, 4800],

[9000, 8500, 9500]])

Perform the following:

a. Calculate the total steps recorded.

b. Calculate the mean number of steps.

c. Find the maximum and minimum values.

d. Calculate the total steps for each day using axis=0.

e. Calculate the total steps for each user using axis=1.

f. Find the user/day position containing the maximum number of steps using argmax().

In [4]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Steps matrix:")
print(steps)

# a
print("\nTotal steps:", steps.sum())

# b
print("Mean steps:", steps.mean())

# c
print("Maximum:", steps.max())
print("Minimum:", steps.min())

# d
print("\nTotal steps for each day:")
print(steps.sum(axis=0))

# e
print("\nTotal steps for each user:")
print(steps.sum(axis=1))

# f
position = np.unravel_index(np.argmax(steps), steps.shape)

print("\nPosition of maximum:", position)
print("Maximum value:", steps[position])

Steps matrix:
[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]

Total steps: 84200
Mean steps: 7016.666666666667
Maximum: 9500
Minimum: 4500

Total steps for each day:
[26500 27300 30400]

Total steps for each user:
[18300 24500 14400 27000]

Position of maximum: (np.int64(3), np.int64(2))
Maximum value: 9500


Q3. Write a Python program using NumPy to perform the following operations:

a. Create the following NumPy array:
original = np.array([1, 2, 3, 4, 5, 6])

b. Create a slice containing elements from index 1 to 4 and store it in a variable named subset.

c. Modify the first element of subset to 999 and display both original and subset.

d. Create another slice from original, but this time use .copy(). Modify its first element to 500
and display original and the copied array.

e. Create a NumPy array containing the numbers from 1 to 12 using np.arange() and reshape it
into a 3 × 4 matrix.

f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing:
• First row
• Last row
• Second column
• Elements from rows 1–2 and columns 2–3

g. Create a flattened version of the 3 × 4 matrix using both flatten() and ravel().

h. Modify an element in the array returned by ravel() and observe whether the original array is
affected.

i. Modify an element in the array returned by flatten() and observe whether the original array is
affected.

j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix

In [5]:
# a
original = np.array([1, 2, 3, 4, 5, 6])

print("Original:")
print(original)

# b
subset = original[1:4]

print("\nSubset:")
print(subset)

# c
subset[0] = 999

print("\nAfter modifying subset:")
print("Original:", original)
print("Subset:", subset)

# d
copied = original[1:4].copy()

copied[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied:", copied)

# e
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)

print("\n3 x 4 Matrix:")
print(matrix)

# f
print("\nFirst row:")
print(matrix[0])

print("\nLast row:")
print(matrix[-1])

print("\nSecond column:")
print(matrix[:, 1])

print("\nRows 1-2 and columns 2-3:")
print(matrix[1:3, 2:4])

# g
flattened = matrix.flatten()
raveled = matrix.ravel()

print("\nFlatten:")
print(flattened)

print("\nRavel:")
print(raveled)

# h
raveled[0] = 999

print("\nAfter modifying ravel:")
print("Raveled:", raveled)
print("Original matrix:")
print(matrix)

# i
flattened[0] = 500

print("\nAfter modifying flatten:")
print("Flattened:", flattened)
print("Original matrix:")
print(matrix)

# j
print("\nShape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original:
[1 2 3 4 5 6]

Subset:
[2 3 4]

After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4]

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied: [500   3   4]

3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row:
[1 2 3 4]

Last row:
[ 9 10 11 12]

Second column:
[ 2  6 10]

Rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]

Flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Ravel:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel:
Raveled: [999   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

After modifying flatten:
Flattened: [500   2   3   4   5   6   7   8   9  10  11  12]
Original matrix:
[[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


Q4. A simple cognitive-assistive system wants to predict a user's assistance score based
on three factors:

• Sleep hours

• Activity level

• Stress level

Consider:

X = np.array([

[6, 70, 3],

[5, 50, 6],

[8, 80, 2],

[4, 30, 8]

])

y = np.array([40, 65, 30, 85])

Here, each row represents one user and each column represents a feature.
Perform the following:
a. Display the shape and dimensions of X.

b. Calculate: X.T and explain what the transpose represents.

c. Calculate the matrix product: X.T @ X

d. Calculate the matrix inverse using: np.linalg.inv() where appropriate.

e. Implement the Ordinary Least Squares equation: 𝛽 = (𝑋!𝑋)"#𝑋!𝑦 using NumPy.

f. Explain what the resulting coefficients represent in the context of the three user
features.

g. A new user has: new_user = np.array([5, 40, 7]) Use your calculated coefficients to
obtain a predicted assistance score.

In [6]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
], dtype=float)

y = np.array([40, 65, 30, 85], dtype=float)

# a. Shape and dimensions
print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

# b. Transpose
print("\nX.T:")
print(X.T)

# c. X.T @ X
XtX = X.T @ X

print("\nX.T @ X:")
print(XtX)

# d. Inverse
XtX_inv = np.linalg.inv(XtX)

print("\nInverse of X.T @ X:")
print(XtX_inv)

# e. OLS coefficients
beta = XtX_inv @ X.T @ y

print("\nOLS coefficients:")
print(beta)

# f. Explain coefficients
print("\nCoefficients:")
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])

# g. Prediction for new user
new_user = np.array([5, 40, 7], dtype=float)

prediction = new_user @ beta

print("\nNew user:", new_user)
print("Predicted assistance score:", prediction)

Shape of X: (4, 3)
Dimensions of X: 2

X.T:
[[ 6.  5.  8.  4.]
 [70. 50. 80. 30.]
 [ 3.  6.  2.  8.]]

X.T @ X:
[[  141.  1430.    96.]
 [ 1430. 14700.   910.]
 [   96.   910.   113.]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS coefficients:
[-0.15921454  0.14083853 10.06302242]

Coefficients:
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587

New user: [ 5. 40.  7.]
Predicted assistance score: 75.27862544779117
