Assignment-4
NumPy-Introduction-1

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [1]:
import numpy as np

import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)

print("After adding 2:", arr + 2)

print("After multiplying by 3:", arr * 3)

print("After dividing by 2:", arr / 2)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])

reversed_arr = arr[::-1]

print("Reversed array:", reversed_arr)


x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)

max_count = counts.max()

most_frequent = values[counts == max_count]

print("Array x:", x)
print("Most frequent value:", most_frequent)
print("Frequency:", max_count)

for value in most_frequent:
    indices = np.where(x == value)[0]
    print("Indices of", value, ":", indices)


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

max_count = counts.max()

most_frequent = values[counts == max_count]

print("Array y:", y)
print("Most frequent values:", most_frequent)
print("Frequency:", max_count)

for value in most_frequent:
    indices = np.where(y == value)[0]
    print("Indices of", value, ":", indices)

Reversed array: [5 4 6 3 2 1]
Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: [1]
Frequency: 5
Indices of 1 : [0 5 7 8 9]
Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent values: [1 3]
Frequency: 3
Indices of 1 : [0 1 2]
Indices of 3 : [4 8 9]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [3]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Array:")
print(arr)

print("1st row, 2nd column:", arr[0, 1])

print("3rd row, 1st column:", arr[2, 0])

Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named < Your Name > with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [9]:
Samuel_Masih = np.linspace(10, 100, 25)

print("Array:")
print(Samuel_Masih)

print("Dimensions:", Samuel_Masih.ndim)

print("Shape:", Samuel_Masih.shape)

print("Total elements:", Samuel_Masih.size)

print("Data type:", Samuel_Masih.dtype)

print("Total bytes:", Samuel_Masih.nbytes)

transpose_array = Samuel_Masih.reshape(25, 1)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200


In [10]:
print("Original shape:", Samuel_Masih.shape)

reshaped = Samuel_Masih.reshape(25, 1)

print("After reshape(25,1):")
print(reshaped)

print("Shape after reshape:", reshaped.shape)

print("Shape of original .T:", Samuel_Masih.T.shape)

transpose_using_T = Samuel_Masih.reshape(1, 25).T

print("Shape after reshape(1,25).T:", transpose_using_T.shape)

Original shape: (25,)
After reshape(25,1):
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Shape after reshape: (25, 1)
Shape of original .T: (25,)
Shape after reshape(1,25).T: (25, 1)


Q: Does .T transpose a 1-D NumPy array?

Answer: A 1-D NumPy array has no row/column orientation, so .T does not change its shape. We need to reshape it into 2-D first if we want a row or column vector.

Q5. Create a 2-D Array of three rows and four columns, named ucs420_ < your_name>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_< your_name>. Resize the array to two rows and three
columns and name it as resized_ ucs420_< your_name>

In [13]:
ucs420_Samuel_Masih = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_Samuel_Masih)

print("\nMean:", np.mean(ucs420_Samuel_Masih))

print("Median:", np.median(ucs420_Samuel_Masih))

print("Maximum:", np.max(ucs420_Samuel_Masih))

print("Minimum:", np.min(ucs420_Samuel_Masih))

print("Unique elements:", np.unique(ucs420_Samuel_Masih))

# Reshape
reshaped_ucs420_Samuel_Masih = ucs420_Samuel_Masih.reshape(4, 3)

print("\nReshaped Array (4 x 3):")
print(reshaped_ucs420_Samuel_Masih)

# Resize
resized_ucs420_Samuel_Masih = np.resize(ucs420_Samuel_Masih, (2, 3))

print("\nResized Array (2 x 3):")
print(resized_ucs420_Samuel_Masih)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
